services:
  - type: web
    name: 1downloader-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true

  - type: static
    name: 1downloader-frontend
    staticPublishPath: ./static
    buildCommand: ""
    envVars:
      - key: API_URL
        value: https://1downloader-backend.onrender.com/api

  - type: cron
    name: cleanup-job
    schedule: "*/5 * * * *"  # Every 5 minutes
    command: "bash cleanup.sh"
