services:
  - type: web
    name: 1downloader
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers 2 --threads 4 --bind 0.0.0.0:$PORT"
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
